<?php

namespace App\Infrastructure\Security\Voters;

final class ListPermissions
{

    // BENCHMARK
    // -----------------------------------------------------------------------------------------------------------------
    public const PERMISSION_BENCHMARK_LIST = 'PERMISSION_BENCHMARK_LIST';
    public const PERMISSION_BENCHMARK_VIEW = 'PERMISSION_BENCHMARK_VIEW';
    public const PERMISSION_BENCHMARK_MANAGE = 'PERMISSION_BENCHMARK_MANAGE';
    public const PERMISSION_BENCHMARK_CREATE = 'PERMISSION_BENCHMARK_CREATE';
    public const PERMISSION_BENCHMARK_EDIT = 'PERMISSION_BENCHMARK_EDIT';
    public const PERMISSION_BENCHMARK_DELETE = 'PERMISSION_BENCHMARK_DELETE';
    public const PERMISSION_CONTENT_BENCHMARK_LIST = 'PERMISSION_CONTENT_BENCHMARK_LIST';
    public const PERMISSION_CONTENT_BENCHMARK_MANAGE = 'PERMISSION_CONTENT_BENCHMARK_MANAGE';
    public const PERMISSION_CONTENT_BENCHMARK_CREATE = 'PERMISSION_CONTENT_BENCHMARK_CREATE';
    public const PERMISSION_CONTENT_BENCHMARK_EDIT = 'PERMISSION_CONTENT_BENCHMARK_EDIT';
    public const PERMISSION_CONTENT_BENCHMARK_DELETE = 'PERMISSION_CONTENT_BENCHMARK_DELETE';

    public const PERMISSION_BENCHMARK_SCORE_LIST = 'PERMISSION_BENCHMARK_SCORE_LIST';
    public const PERMISSION_BENCHMARK_SCORE_VIEW = 'PERMISSION_BENCHMARK_SCORE_VIEW';
    public const PERMISSION_BENCHMARK_SCORE_MANAGE = 'PERMISSION_BENCHMARK_SCORE_MANAGE';
    public const PERMISSION_BENCHMARK_SCORE_CREATE = 'PERMISSION_BENCHMARK_SCORE_CREATE';
    public const PERMISSION_BENCHMARK_SCORE_EDIT = 'PERMISSION_BENCHMARK_SCORE_EDIT';
    public const PERMISSION_BENCHMARK_SCORE_DELETE = 'PERMISSION_BENCHMARK_SCORE_DELETE';


    // EQUIPMENT
    // -----------------------------------------------------------------------------------------------------------------
    public const PERMISSION_EQUIPMENT_LIST = 'PERMISSION_EQUIPMENT_LIST';
    public const PERMISSION_EQUIPMENT_VIEW = 'PERMISSION_EQUIPMENT_VIEW';
    public const PERMISSION_EQUIPMENT_MANAGE = 'PERMISSION_EQUIPMENT_MANAGE';
    public const PERMISSION_EQUIPMENT_CREATE = 'PERMISSION_EQUIPMENT_CREATE';
    public const PERMISSION_EQUIPMENT_EDIT = 'PERMISSION_EQUIPMENT_EDIT';
    public const PERMISSION_EQUIPMENT_DELETE = 'PERMISSION_EQUIPMENT_DELETE';
    public const PERMISSION_CONTENT_EQUIPMENT_LIST = 'PERMISSION_CONTENT_EQUIPMENT_LIST';
    public const PERMISSION_CONTENT_EQUIPMENT_MANAGE = 'PERMISSION_CONTENT_EQUIPMENT_MANAGE';
    public const PERMISSION_CONTENT_EQUIPMENT_CREATE = 'PERMISSION_CONTENT_EQUIPMENT_CREATE';
    public const PERMISSION_CONTENT_EQUIPMENT_EDIT = 'PERMISSION_CONTENT_EQUIPMENT_EDIT';
    public const PERMISSION_CONTENT_EQUIPMENT_DELETE = 'PERMISSION_CONTENT_EQUIPMENT_DELETE';


    // EXERCISE
    // -----------------------------------------------------------------------------------------------------------------
    public const PERMISSION_EXERCISE_LIST = 'PERMISSION_EXERCISE_LIST';
    public const PERMISSION_EXERCISE_VIEW = 'PERMISSION_EXERCISE_VIEW';
    public const PERMISSION_EXERCISE_MANAGE = 'PERMISSION_EXERCISE_MANAGE';
    public const PERMISSION_EXERCISE_CREATE = 'PERMISSION_EXERCISE_CREATE';
    public const PERMISSION_EXERCISE_EDIT = 'PERMISSION_EXERCISE_EDIT';
    public const PERMISSION_EXERCISE_DELETE = 'PERMISSION_EXERCISE_DELETE';
    public const PERMISSION_CONTENT_EXERCISE_LIST = 'PERMISSION_CONTENT_EXERCISE_LIST';
    public const PERMISSION_CONTENT_EXERCISE_MANAGE = 'PERMISSION_CONTENT_EXERCISE_MANAGE';
    public const PERMISSION_CONTENT_EXERCISE_CREATE = 'PERMISSION_CONTENT_EXERCISE_CREATE';
    public const PERMISSION_CONTENT_EXERCISE_EDIT = 'PERMISSION_CONTENT_EXERCISE_EDIT';
    public const PERMISSION_CONTENT_EXERCISE_DELETE = 'PERMISSION_CONTENT_EXERCISE_DELETE';

    public const PERMISSION_EXERCISE_CATEGORY_LIST = 'PERMISSION_EXERCISE_CATEGORY_LIST';
    public const PERMISSION_EXERCISE_CATEGORY_VIEW = 'PERMISSION_EXERCISE_CATEGORY_VIEW';
    public const PERMISSION_EXERCISE_CATEGORY_MANAGE = 'PERMISSION_EXERCISE_CATEGORY_MANAGE';
    public const PERMISSION_EXERCISE_CATEGORY_CREATE = 'PERMISSION_EXERCISE_CATEGORY_CREATE';
    public const PERMISSION_EXERCISE_CATEGORY_EDIT = 'PERMISSION_EXERCISE_CATEGORY_EDIT';
    public const PERMISSION_EXERCISE_CATEGORY_DELETE = 'PERMISSION_EXERCISE_CATEGORY_DELETE';
    public const PERMISSION_CONTENT_EXERCISE_CATEGORY_LIST = 'PERMISSION_CONTENT_EXERCISE_CATEGORY_LIST';
    public const PERMISSION_CONTENT_EXERCISE_CATEGORY_MANAGE = 'PERMISSION_CONTENT_EXERCISE_CATEGORY_MANAGE';
    public const PERMISSION_CONTENT_EXERCISE_CATEGORY_CREATE = 'PERMISSION_CONTENT_EXERCISE_CATEGORY_CREATE';
    public const PERMISSION_CONTENT_EXERCISE_CATEGORY_EDIT = 'PERMISSION_CONTENT_EXERCISE_CATEGORY_EDIT';
    public const PERMISSION_CONTENT_EXERCISE_CATEGORY_DELETE = 'PERMISSION_CONTENT_EXERCISE_CATEGORY_DELETE';


    // MUSCLE
    // -----------------------------------------------------------------------------------------------------------------
    public const PERMISSION_MUSCLE_LIST = 'PERMISSION_MUSCLE_LIST';
    public const PERMISSION_MUSCLE_VIEW = 'PERMISSION_MUSCLE_VIEW';
    public const PERMISSION_MUSCLE_MANAGE = 'PERMISSION_MUSCLE_MANAGE';
    public const PERMISSION_MUSCLE_CREATE = 'PERMISSION_MUSCLE_CREATE';
    public const PERMISSION_MUSCLE_EDIT = 'PERMISSION_MUSCLE_EDIT';
    public const PERMISSION_MUSCLE_DELETE = 'PERMISSION_MUSCLE_DELETE';
    public const PERMISSION_CONTENT_MUSCLE_LIST = 'PERMISSION_CONTENT_MUSCLE_LIST';
    public const PERMISSION_CONTENT_MUSCLE_MANAGE = 'PERMISSION_CONTENT_MUSCLE_MANAGE';
    public const PERMISSION_CONTENT_MUSCLE_CREATE = 'PERMISSION_CONTENT_MUSCLE_CREATE';
    public const PERMISSION_CONTENT_MUSCLE_EDIT = 'PERMISSION_CONTENT_MUSCLE_EDIT';
    public const PERMISSION_CONTENT_MUSCLE_DELETE = 'PERMISSION_CONTENT_MUSCLE_DELETE';

    public const PERMISSION_MUSCLE_AREA_LIST = 'PERMISSION_MUSCLE_AREA_LIST';
    public const PERMISSION_MUSCLE_AREA_VIEW = 'PERMISSION_MUSCLE_AREA_VIEW';
    public const PERMISSION_MUSCLE_AREA_MANAGE = 'PERMISSION_MUSCLE_AREA_MANAGE';
    public const PERMISSION_MUSCLE_AREA_CREATE = 'PERMISSION_MUSCLE_AREA_CREATE';
    public const PERMISSION_MUSCLE_AREA_EDIT = 'PERMISSION_MUSCLE_AREA_EDIT';
    public const PERMISSION_MUSCLE_AREA_DELETE = 'PERMISSION_MUSCLE_AREA_DELETE';
    public const PERMISSION_CONTENT_MUSCLE_AREA_LIST = 'PERMISSION_CONTENT_MUSCLE_AREA_LIST';
    public const PERMISSION_CONTENT_MUSCLE_AREA_MANAGE = 'PERMISSION_CONTENT_MUSCLE_AREA_MANAGE';
    public const PERMISSION_CONTENT_MUSCLE_AREA_CREATE = 'PERMISSION_CONTENT_MUSCLE_AREA_CREATE';
    public const PERMISSION_CONTENT_MUSCLE_AREA_EDIT = 'PERMISSION_CONTENT_MUSCLE_AREA_EDIT';
    public const PERMISSION_CONTENT_MUSCLE_AREA_DELETE = 'PERMISSION_CONTENT_MUSCLE_AREA_DELETE';

    public const PERMISSION_MUSCLE_GROUP_LIST = 'PERMISSION_MUSCLE_GROUP_LIST';
    public const PERMISSION_MUSCLE_GROUP_VIEW = 'PERMISSION_MUSCLE_GROUP_VIEW';
    public const PERMISSION_MUSCLE_GROUP_MANAGE = 'PERMISSION_MUSCLE_GROUP_MANAGE';
    public const PERMISSION_MUSCLE_GROUP_CREATE = 'PERMISSION_MUSCLE_GROUP_CREATE';
    public const PERMISSION_MUSCLE_GROUP_EDIT = 'PERMISSION_MUSCLE_GROUP_EDIT';
    public const PERMISSION_MUSCLE_GROUP_DELETE = 'PERMISSION_MUSCLE_GROUP_DELETE';
    public const PERMISSION_CONTENT_MUSCLE_GROUP_LIST = 'PERMISSION_CONTENT_MUSCLE_GROUP_LIST';
    public const PERMISSION_CONTENT_MUSCLE_GROUP_MANAGE = 'PERMISSION_CONTENT_MUSCLE_GROUP_MANAGE';
    public const PERMISSION_CONTENT_MUSCLE_GROUP_CREATE = 'PERMISSION_CONTENT_MUSCLE_GROUP_CREATE';
    public const PERMISSION_CONTENT_MUSCLE_GROUP_EDIT = 'PERMISSION_CONTENT_MUSCLE_GROUP_EDIT';
    public const PERMISSION_CONTENT_MUSCLE_GROUP_DELETE = 'PERMISSION_CONTENT_MUSCLE_GROUP_DELETE';


    // SECURITY
    // -----------------------------------------------------------------------------------------------------------------
    public const PERMISSION_USER_LIST = 'PERMISSION_USER_LIST';
    public const PERMISSION_USER_VIEW = 'PERMISSION_USER_VIEW';
    public const PERMISSION_USER_MANAGE = 'PERMISSION_USER_MANAGE';
    public const PERMISSION_USER_CREATE = 'PERMISSION_USER_CREATE';
    public const PERMISSION_USER_EDIT = 'PERMISSION_USER_EDIT';
    public const PERMISSION_USER_DELETE = 'PERMISSION_USER_DELETE';

    public const PERMISSION_ROLE_LIST = 'PERMISSION_ROLE_LIST';
    public const PERMISSION_ROLE_VIEW = 'PERMISSION_ROLE_VIEW';
    public const PERMISSION_ROLE_MANAGE = 'PERMISSION_ROLE_MANAGE';
    public const PERMISSION_ROLE_CREATE = 'PERMISSION_ROLE_CREATE';
    public const PERMISSION_ROLE_EDIT = 'PERMISSION_ROLE_EDIT';
    public const PERMISSION_ROLE_DELETE = 'PERMISSION_ROLE_DELETE';

    public const PERMISSION_PERMISSION_LIST = 'PERMISSION_PERMISSION_LIST';
    public const PERMISSION_PERMISSION_VIEW = 'PERMISSION_PERMISSION_VIEW';
    public const PERMISSION_PERMISSION_MANAGE = 'PERMISSION_PERMISSION_MANAGE';
    public const PERMISSION_PERMISSION_CREATE = 'PERMISSION_PERMISSION_CREATE';
    public const PERMISSION_PERMISSION_EDIT = 'PERMISSION_PERMISSION_EDIT';
    public const PERMISSION_PERMISSION_DELETE = 'PERMISSION_PERMISSION_DELETE';


    // WOD
    // -----------------------------------------------------------------------------------------------------------------
    public const PERMISSION_WOD_LIST = 'PERMISSION_WOD_LIST';
    public const PERMISSION_WOD_VIEW = 'PERMISSION_WOD_VIEW';
    public const PERMISSION_WOD_MANAGE = 'PERMISSION_WOD_MANAGE';
    public const PERMISSION_WOD_CREATE = 'PERMISSION_WOD_CREATE';
    public const PERMISSION_WOD_EDIT = 'PERMISSION_WOD_EDIT';
    public const PERMISSION_WOD_DELETE = 'PERMISSION_WOD_DELETE';

    public const PERMISSION_WOD_AGE_RANGE_LIST = 'PERMISSION_WOD_AGE_RANGE_LIST';
    public const PERMISSION_WOD_AGE_RANGE_VIEW = 'PERMISSION_WOD_AGE_RANGE_VIEW';
    public const PERMISSION_WOD_AGE_RANGE_MANAGE = 'PERMISSION_WOD_AGE_RANGE_MANAGE';
    public const PERMISSION_WOD_AGE_RANGE_CREATE = 'PERMISSION_WOD_AGE_RANGE_CREATE';
    public const PERMISSION_WOD_AGE_RANGE_EDIT = 'PERMISSION_WOD_AGE_RANGE_EDIT';
    public const PERMISSION_WOD_AGE_RANGE_DELETE = 'PERMISSION_WOD_AGE_RANGE_DELETE';
    public const PERMISSION_CONTENT_WOD_AGE_RANGE_LIST = 'PERMISSION_CONTENT_WOD_AGE_RANGE_LIST';
    public const PERMISSION_CONTENT_WOD_AGE_RANGE_MANAGE = 'PERMISSION_CONTENT_WOD_AGE_RANGE_MANAGE';
    public const PERMISSION_CONTENT_WOD_AGE_RANGE_CREATE = 'PERMISSION_CONTENT_WOD_AGE_RANGE_CREATE';
    public const PERMISSION_CONTENT_WOD_AGE_RANGE_EDIT = 'PERMISSION_CONTENT_WOD_AGE_RANGE_EDIT';
    public const PERMISSION_CONTENT_WOD_AGE_RANGE_DELETE = 'PERMISSION_CONTENT_WOD_AGE_RANGE_DELETE';

    public const PERMISSION_WOD_CATEGORY_LIST = 'PERMISSION_WOD_CATEGORY_LIST';
    public const PERMISSION_WOD_CATEGORY_VIEW = 'PERMISSION_WOD_CATEGORY_VIEW';
    public const PERMISSION_WOD_CATEGORY_MANAGE = 'PERMISSION_WOD_CATEGORY_MANAGE';
    public const PERMISSION_WOD_CATEGORY_CREATE = 'PERMISSION_WOD_CATEGORY_CREATE';
    public const PERMISSION_WOD_CATEGORY_EDIT = 'PERMISSION_WOD_CATEGORY_EDIT';
    public const PERMISSION_WOD_CATEGORY_DELETE = 'PERMISSION_WOD_CATEGORY_DELETE';
    public const PERMISSION_CONTENT_WOD_CATEGORY_LIST = 'PERMISSION_CONTENT_WOD_CATEGORY_LIST';
    public const PERMISSION_CONTENT_WOD_CATEGORY_MANAGE = 'PERMISSION_CONTENT_WOD_CATEGORY_MANAGE';
    public const PERMISSION_CONTENT_WOD_CATEGORY_CREATE = 'PERMISSION_CONTENT_WOD_CATEGORY_CREATE';
    public const PERMISSION_CONTENT_WOD_CATEGORY_EDIT = 'PERMISSION_CONTENT_WOD_CATEGORY_EDIT';
    public const PERMISSION_CONTENT_WOD_CATEGORY_DELETE = 'PERMISSION_CONTENT_WOD_CATEGORY_DELETE';

    public const PERMISSION_WOD_DIVISION_LIST = 'PERMISSION_WOD_DIVISION_LIST';
    public const PERMISSION_WOD_DIVISION_VIEW = 'PERMISSION_WOD_DIVISION_VIEW';
    public const PERMISSION_WOD_DIVISION_MANAGE = 'PERMISSION_WOD_DIVISION_MANAGE';
    public const PERMISSION_WOD_DIVISION_CREATE = 'PERMISSION_WOD_DIVISION_CREATE';
    public const PERMISSION_WOD_DIVISION_EDIT = 'PERMISSION_WOD_DIVISION_EDIT';
    public const PERMISSION_WOD_DIVISION_DELETE = 'PERMISSION_WOD_DIVISION_DELETE';
    public const PERMISSION_CONTENT_WOD_DIVISION_LIST = 'PERMISSION_CONTENT_WOD_DIVISION_LIST';
    public const PERMISSION_CONTENT_WOD_DIVISION_MANAGE = 'PERMISSION_CONTENT_WOD_DIVISION_MANAGE';
    public const PERMISSION_CONTENT_WOD_DIVISION_CREATE = 'PERMISSION_CONTENT_WOD_DIVISION_CREATE';
    public const PERMISSION_CONTENT_WOD_DIVISION_EDIT = 'PERMISSION_CONTENT_WOD_DIVISION_EDIT';
    public const PERMISSION_CONTENT_WOD_DIVISION_DELETE = 'PERMISSION_CONTENT_WOD_DIVISION_DELETE';

    public const PERMISSION_WOD_TYPE_LIST = 'PERMISSION_WOD_TYPE_LIST';
    public const PERMISSION_WOD_TYPE_VIEW = 'PERMISSION_WOD_TYPE_VIEW';
    public const PERMISSION_WOD_TYPE_MANAGE = 'PERMISSION_WOD_TYPE_MANAGE';
    public const PERMISSION_WOD_TYPE_CREATE = 'PERMISSION_WOD_TYPE_CREATE';
    public const PERMISSION_WOD_TYPE_EDIT = 'PERMISSION_WOD_TYPE_EDIT';
    public const PERMISSION_WOD_TYPE_DELETE = 'PERMISSION_WOD_TYPE_DELETE';
    public const PERMISSION_CONTENT_WOD_TYPE_LIST = 'PERMISSION_CONTENT_WOD_TYPE_LIST';
    public const PERMISSION_CONTENT_WOD_TYPE_MANAGE = 'PERMISSION_CONTENT_WOD_TYPE_MANAGE';
    public const PERMISSION_CONTENT_WOD_TYPE_CREATE = 'PERMISSION_CONTENT_WOD_TYPE_CREATE';
    public const PERMISSION_CONTENT_WOD_TYPE_EDIT = 'PERMISSION_CONTENT_WOD_TYPE_EDIT';
    public const PERMISSION_CONTENT_WOD_TYPE_DELETE = 'PERMISSION_CONTENT_WOD_TYPE_DELETE';

    public const PERMISSION_WOD_VERSION_LIST = 'PERMISSION_WOD_VERSION_LIST';
    public const PERMISSION_WOD_VERSION_VIEW = 'PERMISSION_WOD_VERSION_VIEW';
    public const PERMISSION_WOD_VERSION_MANAGE = 'PERMISSION_WOD_VERSION_MANAGE';
    public const PERMISSION_WOD_VERSION_CREATE = 'PERMISSION_WOD_VERSION_CREATE';
    public const PERMISSION_WOD_VERSION_EDIT = 'PERMISSION_WOD_VERSION_EDIT';
    public const PERMISSION_WOD_VERSION_DELETE = 'PERMISSION_WOD_VERSION_DELETE';
    public const PERMISSION_CONTENT_WOD_VERSION_LIST = 'PERMISSION_CONTENT_WOD_VERSION_LIST';
    public const PERMISSION_CONTENT_WOD_VERSION_MANAGE = 'PERMISSION_CONTENT_WOD_VERSION_MANAGE';
    public const PERMISSION_CONTENT_WOD_VERSION_CREATE = 'PERMISSION_CONTENT_WOD_VERSION_CREATE';
    public const PERMISSION_CONTENT_WOD_VERSION_EDIT = 'PERMISSION_CONTENT_WOD_VERSION_EDIT';
    public const PERMISSION_CONTENT_WOD_VERSION_DELETE = 'PERMISSION_CONTENT_WOD_VERSION_DELETE';

    public const PERMISSION_WOD_SCORE_LIST = 'PERMISSION_WOD_SCORE_LIST';
    public const PERMISSION_WOD_SCORE_VIEW = 'PERMISSION_WOD_SCORE_VIEW';
    public const PERMISSION_WOD_SCORE_MANAGE = 'PERMISSION_WOD_SCORE_MANAGE';
    public const PERMISSION_WOD_SCORE_CREATE = 'PERMISSION_WOD_SCORE_CREATE';
    public const PERMISSION_WOD_SCORE_EDIT = 'PERMISSION_WOD_SCORE_EDIT';
    public const PERMISSION_WOD_SCORE_DELETE = 'PERMISSION_WOD_SCORE_DELETE';
}