services:
    nginx:
        image: nginx:latest
        volumes:
            - ./docker/nginx/api.conf:/etc/nginx/conf.d/api.conf
            - ./docker/nginx/front.conf:/etc/nginx/conf.d/front.conf
            - ./docker/nginx/admin.conf:/etc/nginx/conf.d/admin.conf
            - ./docker/nginx/websocket.conf:/etc/nginx/conf.d/websocket.conf
            - ./docker/nginx/ssl:/etc/nginx/ssl
            - ./api/public:/app/public
        ports:
            - "80:80"
            - "443:443"
        networks:
            - app-network
        depends_on:
            - api
            - react
            - admin
        restart: unless-stopped

    api:
        build:
            context: ./docker/php
        volumes:
            - ./api:/app
        networks:
            - app-network
        depends_on:
            - db
        restart: unless-stopped

    db:
        image: percona/percona-server:8.0
        environment:
            MYSQL_ROOT_PASSWORD: root_password
            MYSQL_DATABASE: symfony_db
            MYSQL_USER: symfony_user
            MYSQL_PASSWORD: symfony_password
        ports:
            - "3306:3306"
        volumes:
            - percona-data:/var/lib/mysql
        networks:
            - app-network
        restart: unless-stopped

    react:
        build:
            context: .
            dockerfile: ./docker/node-front/Dockerfile
        volumes:
            - ./front:/app
            - /app/node_modules
            - /app/apps/web/node_modules
            - /app/packages/ui/node_modules
            - /app/packages/api/node_modules
            - /app/packages/eslint-config/node_modules
            - /app/packages/typescript-config/node_modules
        networks:
            - app-network
        command: ["pnpm", "--filter", "web", "dev"]
        depends_on:
            - api
        restart: on-failure

    websocket:
        build:
            context: ./docker/node
        volumes:
            - ./websocket:/app
        networks:
            - app-network
        command: ["sh", "-c", "yarn install && yarn run start --host 0.0.0.0 --port 4000"]
        depends_on:
            - api
            - react
        restart: unless-stopped

    admin:
        build:
            context: .
            dockerfile: ./docker/node-front/Dockerfile
        volumes:
            - ./front:/app
            - /app/node_modules
            - /app/apps/admin/node_modules
            - /app/packages/ui/node_modules
            - /app/packages/api/node_modules
            - /app/packages/eslint-config/node_modules
            - /app/packages/typescript-config/node_modules
        networks:
            - app-network
        command: ["pnpm", "--filter", "admin", "dev"]
        depends_on:
            - api
        restart: on-failure

networks:
    app-network:
        name: app-network
        driver: bridge

volumes:
    percona-data:
