security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
            algorithm: auto
    
    providers:
        app_user_provider:
            entity:
                class: App\Domain\User\Entity\User
                property: email
    
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        login:
            pattern: ^/auth/login
            stateless: true
            json_login:
                check_path: /auth/login
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        register:
            pattern: ^/auth/register
            stateless: true
            security: false

        refresh:
            pattern: ^/auth/token/refresh
            stateless: true
            refresh_jwt: ~
        
        api:
            pattern: ^/
            stateless: true
            entry_point: jwt
            jwt: ~
            custom_authenticators:
                - App\Infrastructure\Security\ApiKey\ApiKeyAuthenticator
    
    access_control:
        # Routes publiques
        - { path: ^/auth/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/auth/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/auth/token/refresh, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        
        # Routes protégées
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
