controllers:
    resource:
        path: ../src/UI/Http/Controller/
        namespace: App\UI\Http\Controller
    type: attribute
    prefix: /{_locale}
    requirements:
        _locale: en|fr
    defaults:
        _locale: en
    
api_login_check:
    path: /auth/login
    prefix: /